[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "wash zone great replace kingdom letter anger response actual visit focus letter"
stx-address = "ST12JJRGZECY58KTESA0KFPZR68GQRK6T0CDNK3Z4"